pipeline {
    agent any

    tools {
        jdk 'JAVA_HOME'
        maven 'M2_HOME'
    }

    stages {
        stage('Checkout Backend') {
            steps {
                echo ' Récupération du code source...'
                checkout scm
            }
        }

        stage('Compilation Maven') {
            steps {
                echo ' Compilation du projet Spring Boot...'
                dir('backend') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Test & Package') {
            steps {
                echo ' Exécution des tests et génération du livrable JAR...'
                dir('backend') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
    }

    post {
        success {
            echo ' Backend compilé et packagé avec succès !'
        }
        failure {
            echo ' Échec lors du build Backend !'
        }
    }
}
